"""PILOT-0001 adapter: the properties the treatment definition promises.

Three of these are named in the contract as things implementation must prove:
cross-kind validation is impossible, frozen settlement is impossible, and
ephemeral state cannot survive a trial boundary.
"""

import re
import sys
import tempfile
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "runtime"))
sys.path.insert(0, str(ROOT / "experiment" / "PILOT-0001"))

# The split in these two imports is the packaging boundary. Kind-awareness is
# generic and ships; the pilot adapter is reached through a path the installer
# never copies.
from howdo import (  # noqa: E402
    ContextKindError,
    KIND_ENVIRONMENT,
    KIND_PERSON,
    complete_onboarding,
    context_kind,
    inspect_context,
)
from adapter import (  # noqa: E402
    FrozenContextError,
    PilotAdmissibilityError,
    ReconReceipt,
    assert_pilot_admissible,
    close_trial_context,
    complete_reconnaissance,
    describe_frozen,
    freeze_context,
    open_trial_context,
)

TEMPLATE = ROOT / "experiment" / "PILOT-0001" / "ENVIRONMENT.template.md"
TREATMENT = ROOT / "experiment" / "PILOT-0001" / "TREATMENT.md"
PROCEDURE = ROOT / "experiment" / "PILOT-0001" / "reconnaissance.md"

PERSON = """---
howdo_context: "2"
context_id: pending
context_file: CONTEXT.md
skill: how-do
skill_version: "0.8.0"
onboarding: required
parent_context_id: none
---
# How Do Context

## Calibration domains

- pending

## Representation observations

- pending

## Structures that landed

- pending

## Structures that did not land

- pending
"""

RECON = ReconReceipt(
    available_ground="python 3.11, pytest 8.2 and ripgrep are on PATH; repo has tests/ and no CI config",
    imposed_ordering="uv sync must run before pytest; the package is not importable from a clean checkout",
    verification_mechanisms="pytest exit status over tests/ is the verifier; there is no linter configured",
    authority_boundaries="src/ is writable; vendor/ is a read-only mount; build/ is regenerated by make",
    notes="could not determine whether the network is reachable",
)


def _flatten(text: str) -> str:
    return re.sub(r"\s+", " ", text).lower()


def _person(directory: Path) -> Path:
    path = directory / "CONTEXT.md"
    path.write_text(PERSON, encoding="utf-8")
    complete_onboarding(
        path,
        calibration_domain="incident response — can critique triage explanations",
        representation_observation="relation first, then rule, then executable step",
        landed_example="small boundary diagram exposed the missing handoff",
        rejected_example="taxonomy-first prose hid the concrete object",
    )
    return path


def _settled_environment(directory: Path, trial_id: str = "trial-a") -> Path:
    path = directory / "ENVIRONMENT.md"
    open_trial_context(path, template=TEMPLATE, trial_id=trial_id)
    complete_reconnaissance(path, RECON, trial_id=trial_id)
    return path


def _relabel(path: Path, **pairs: str) -> None:
    """Rewrite frontmatter keys, inserting any the file does not carry yet.

    Replacing only what is already there would silently no-op on exactly the
    case these tests exist for: a person context has no ``context_kind`` line,
    so relabelling it has to add one.
    """
    text = path.read_text(encoding="utf-8")
    for key, value in pairs.items():
        pattern = rf"(?m)^{key}:.*$"
        if re.search(pattern, text):
            text = re.sub(pattern, f"{key}: {value}", text)
        else:
            text = text.replace("---\n", f"---\n{key}: {value}\n", 1)
    path.write_text(text, encoding="utf-8")


class KindDisjointnessTests(unittest.TestCase):
    """person and environment are different kinds, not two modes of one onboarding."""

    def test_absent_kind_still_means_person(self):
        with tempfile.TemporaryDirectory() as td:
            path = _person(Path(td))
            self.assertEqual(context_kind(inspect_context(path).metadata), KIND_PERSON)
            self.assertEqual(inspect_context(path).state, "ready")

    def test_shipped_environment_template_is_a_template(self):
        status = inspect_context(TEMPLATE)
        self.assertEqual(status.state, "template", status.reason)
        self.assertEqual(context_kind(status.metadata), KIND_ENVIRONMENT)

    def test_a_person_context_cannot_satisfy_the_environment_validator(self):
        with tempfile.TemporaryDirectory() as td:
            path = _person(Path(td))
            self.assertEqual(inspect_context(path).state, "ready")
            _relabel(path, context_kind=KIND_ENVIRONMENT)
            status = inspect_context(path, trial_id="trial-a")
            self.assertNotEqual(status.state, "ready")
            self.assertEqual(status.state, "invalid")
            self.assertIn("missing required keys", status.reason)

    def test_an_environment_context_cannot_satisfy_the_person_validator(self):
        with tempfile.TemporaryDirectory() as td:
            path = _settled_environment(Path(td))
            self.assertEqual(inspect_context(path, trial_id="trial-a").state, "ready")
            _relabel(path, context_kind=KIND_PERSON)
            status = inspect_context(path)
            self.assertNotEqual(status.state, "ready")
            self.assertIn("missing required keys", status.reason)
            self.assertIn("onboarding", status.reason)

    def test_person_evidence_sections_do_not_settle_an_environment_context(self):
        """The headings themselves are disjoint, so the text cannot be reused."""
        with tempfile.TemporaryDirectory() as td:
            path = _person(Path(td))
            _relabel(
                path,
                context_kind=KIND_ENVIRONMENT,
                onboarding="complete",
            )
            text = path.read_text(encoding="utf-8")
            text = text.replace(
                "onboarding: complete",
                "reconnaissance: complete\nlifetime: frozen\nwrite_authority: readonly",
            )
            path.write_text(text, encoding="utf-8")
            status = inspect_context(path)
            self.assertEqual(status.state, "reconnaissance_required")
            self.assertIn("Available ground", status.reason)

    def test_onboarding_refuses_an_environment_context(self):
        with tempfile.TemporaryDirectory() as td:
            path = Path(td) / "ENVIRONMENT.md"
            open_trial_context(path, template=TEMPLATE, trial_id="trial-a")
            with self.assertRaises(ContextKindError):
                complete_onboarding(
                    path,
                    calibration_domain="d",
                    representation_observation="r",
                    landed_example="l",
                    rejected_example="x",
                )

    def test_reconnaissance_refuses_a_person_context(self):
        with tempfile.TemporaryDirectory() as td:
            path = Path(td) / "CONTEXT.md"
            path.write_text(PERSON, encoding="utf-8")
            with self.assertRaises(ContextKindError):
                complete_reconnaissance(path, RECON)

    def test_an_unrecognised_kind_is_invalid_not_silently_person(self):
        with tempfile.TemporaryDirectory() as td:
            path = _person(Path(td))
            _relabel(path, context_kind="organisation")
            status = inspect_context(path)
            self.assertEqual(status.state, "invalid")
            self.assertIn("unrecognised context_kind", status.reason)


class TrialBoundaryTests(unittest.TestCase):
    """Ephemeral state cannot survive a trial boundary."""

    def test_a_new_trial_context_needs_reconnaissance(self):
        with tempfile.TemporaryDirectory() as td:
            path = Path(td) / "ENVIRONMENT.md"
            status = open_trial_context(path, template=TEMPLATE, trial_id="trial-a")
            self.assertEqual(status.state, "reconnaissance_required")

    def test_settled_context_is_ready_for_its_own_trial(self):
        with tempfile.TemporaryDirectory() as td:
            path = _settled_environment(Path(td), "trial-a")
            self.assertEqual(inspect_context(path, trial_id="trial-a").state, "ready")

    def test_the_next_trial_cannot_read_the_previous_trials_context(self):
        with tempfile.TemporaryDirectory() as td:
            path = _settled_environment(Path(td), "trial-a")
            status = inspect_context(path, trial_id="trial-b")
            self.assertEqual(status.state, "expired")
            self.assertIn("did not survive the trial boundary", status.reason)

    def test_an_ephemeral_context_cannot_be_read_without_asserting_a_trial(self):
        with tempfile.TemporaryDirectory() as td:
            path = _settled_environment(Path(td), "trial-a")
            status = inspect_context(path)
            self.assertEqual(status.state, "invalid")
            self.assertIn("must be read with the reading trial", status.reason)

    def test_an_unbound_ephemeral_context_is_invalid(self):
        with tempfile.TemporaryDirectory() as td:
            path = _settled_environment(Path(td), "trial-a")
            _relabel(path, trial_id="none")
            status = inspect_context(path, trial_id="trial-a")
            self.assertEqual(status.state, "invalid")
            self.assertIn("not bound to a trial_id", status.reason)

    def test_another_trial_cannot_settle_this_trials_context(self):
        with tempfile.TemporaryDirectory() as td:
            path = Path(td) / "ENVIRONMENT.md"
            open_trial_context(path, template=TEMPLATE, trial_id="trial-a")
            with self.assertRaises(ValueError) as caught:
                complete_reconnaissance(path, RECON, trial_id="trial-b")
            self.assertIn("did not survive the trial boundary", str(caught.exception))

    def test_opening_a_trial_requires_a_concrete_id(self):
        with tempfile.TemporaryDirectory() as td:
            for bad in ("", "  ", "none", "pending"):
                with self.assertRaises(ValueError):
                    open_trial_context(
                        Path(td) / f"E-{bad.strip() or 'blank'}.md",
                        template=TEMPLATE,
                        trial_id=bad,
                    )

    def test_closing_attests_to_what_was_destroyed(self):
        with tempfile.TemporaryDirectory() as td:
            path = _settled_environment(Path(td), "trial-a")
            closure = close_trial_context(path, trial_id="trial-a")
            self.assertFalse(path.exists())
            self.assertEqual(len(closure.digest), 64)
            self.assertGreater(closure.byte_length, 0)

    def test_closing_refuses_another_trials_context(self):
        with tempfile.TemporaryDirectory() as td:
            path = _settled_environment(Path(td), "trial-a")
            with self.assertRaises(ValueError):
                close_trial_context(path, trial_id="trial-b")
            self.assertTrue(path.exists())

    def test_a_trial_context_is_created_once(self):
        with tempfile.TemporaryDirectory() as td:
            path = Path(td) / "ENVIRONMENT.md"
            open_trial_context(path, template=TEMPLATE, trial_id="trial-a")
            with self.assertRaises(FileExistsError):
                open_trial_context(path, template=TEMPLATE, trial_id="trial-a")


class FrozenContextTests(unittest.TestCase):
    """Frozen settlement is impossible, and immutability is externally visible."""

    def test_freezing_produces_a_readonly_file_with_a_matching_digest(self):
        with tempfile.TemporaryDirectory() as td:
            source = _settled_environment(Path(td), "trial-a")
            frozen = freeze_context(source, Path(td) / "FROZEN.md")
            try:
                self.assertTrue(frozen.readonly)
                described = describe_frozen(frozen.path)
                self.assertEqual(described.digest, frozen.digest)
                self.assertTrue(described.readonly, "freeze left the file writable")
                self.assertEqual(described.byte_length, frozen.byte_length)
            finally:
                frozen.path.chmod(0o644)

    def test_a_frozen_context_cannot_be_settled(self):
        with tempfile.TemporaryDirectory() as td:
            source = _settled_environment(Path(td), "trial-a")
            frozen = freeze_context(source, Path(td) / "FROZEN.md")
            try:
                with self.assertRaises(FrozenContextError):
                    complete_reconnaissance(frozen.path, RECON)
            finally:
                frozen.path.chmod(0o644)

    def test_readonly_alone_also_refuses_settlement(self):
        with tempfile.TemporaryDirectory() as td:
            path = Path(td) / "ENVIRONMENT.md"
            open_trial_context(path, template=TEMPLATE, trial_id="trial-a")
            _relabel(path, write_authority="readonly")
            with self.assertRaises(FrozenContextError):
                complete_reconnaissance(path, RECON, trial_id="trial-a")

    def test_only_a_settled_context_can_be_frozen(self):
        with tempfile.TemporaryDirectory() as td:
            path = Path(td) / "ENVIRONMENT.md"
            open_trial_context(path, template=TEMPLATE, trial_id="trial-a")
            with self.assertRaises(ValueError):
                freeze_context(path, Path(td) / "FROZEN.md")

    def test_a_frozen_context_is_a_new_lineage_parented_to_its_source(self):
        with tempfile.TemporaryDirectory() as td:
            source = _settled_environment(Path(td), "trial-a")
            parent = inspect_context(source, trial_id="trial-a").metadata["context_id"]
            frozen = freeze_context(source, Path(td) / "FROZEN.md")
            try:
                metadata = inspect_context(frozen.path).metadata
                self.assertEqual(frozen.created_from, parent)
                self.assertEqual(metadata["parent_context_id"], parent)
                self.assertNotEqual(metadata["context_id"], parent)
            finally:
                frozen.path.chmod(0o644)

    def test_a_frozen_context_is_readable_by_any_trial(self):
        with tempfile.TemporaryDirectory() as td:
            source = _settled_environment(Path(td), "trial-a")
            frozen = freeze_context(source, Path(td) / "FROZEN.md")
            try:
                for trial in ("trial-a", "trial-b", None):
                    self.assertEqual(
                        inspect_context(frozen.path, trial_id=trial).state, "ready"
                    )
            finally:
                frozen.path.chmod(0o644)

    def test_describe_frozen_reports_the_filesystem_not_the_frontmatter(self):
        with tempfile.TemporaryDirectory() as td:
            source = _settled_environment(Path(td), "trial-a")
            frozen = freeze_context(source, Path(td) / "FROZEN.md")
            frozen.path.chmod(0o644)
            self.assertFalse(
                describe_frozen(frozen.path).readonly,
                "a frozen declaration on a writable file must be visible",
            )


class PilotAdmissibilityTests(unittest.TestCase):
    def test_ephemeral_writable_environment_is_admitted(self):
        with tempfile.TemporaryDirectory() as td:
            path = _settled_environment(Path(td), "trial-a")
            self.assertEqual(
                assert_pilot_admissible(path), (KIND_ENVIRONMENT, "ephemeral", "writable")
            )

    def test_frozen_readonly_environment_is_admitted(self):
        with tempfile.TemporaryDirectory() as td:
            source = _settled_environment(Path(td), "trial-a")
            frozen = freeze_context(source, Path(td) / "FROZEN.md")
            try:
                self.assertEqual(
                    assert_pilot_admissible(frozen.path),
                    (KIND_ENVIRONMENT, "frozen", "readonly"),
                )
            finally:
                frozen.path.chmod(0o644)

    def test_persistent_is_prohibited_and_says_why(self):
        with tempfile.TemporaryDirectory() as td:
            path = _settled_environment(Path(td), "trial-a")
            _relabel(path, lifetime="persistent")
            with self.assertRaises(PilotAdmissibilityError) as caught:
                assert_pilot_admissible(path)
            self.assertIn("independence", str(caught.exception))

    def test_a_person_context_is_inadmissible_in_a_trial(self):
        with tempfile.TemporaryDirectory() as td:
            path = _person(Path(td))
            with self.assertRaises(PilotAdmissibilityError) as caught:
                assert_pilot_admissible(path)
            self.assertIn("person context", str(caught.exception))

    def test_mismatched_lifetime_and_authority_are_refused(self):
        with tempfile.TemporaryDirectory() as td:
            path = _settled_environment(Path(td), "trial-a")
            _relabel(path, write_authority="readonly")
            with self.assertRaises(PilotAdmissibilityError):
                assert_pilot_admissible(path)


class ReconnaissanceEvidenceTests(unittest.TestCase):
    def test_completion_requires_an_observation_in_every_section(self):
        with tempfile.TemporaryDirectory() as td:
            path = Path(td) / "ENVIRONMENT.md"
            open_trial_context(path, template=TEMPLATE, trial_id="trial-a")
            with self.assertRaises(ValueError):
                complete_reconnaissance(
                    path,
                    ReconReceipt(
                        available_ground="pytest is on PATH",
                        imposed_ordering="pending",
                        verification_mechanisms="pytest exit status",
                        authority_boundaries="src/ is writable",
                    ),
                    trial_id="trial-a",
                )

    def test_flipping_the_marker_does_not_fake_completion(self):
        with tempfile.TemporaryDirectory() as td:
            path = Path(td) / "ENVIRONMENT.md"
            open_trial_context(path, template=TEMPLATE, trial_id="trial-a")
            _relabel(path, reconnaissance="complete", context_id="context_fake")
            status = inspect_context(path, trial_id="trial-a")
            self.assertEqual(status.state, "reconnaissance_required")
            self.assertIn("missing evidence", status.reason)

    def test_the_template_itself_is_never_settleable(self):
        from howdo import TemplateContextError

        with self.assertRaises(TemplateContextError):
            complete_reconnaissance(TEMPLATE, RECON)

    def test_settling_twice_is_refused(self):
        with tempfile.TemporaryDirectory() as td:
            path = _settled_environment(Path(td), "trial-a")
            with self.assertRaises(ValueError):
                complete_reconnaissance(path, RECON, trial_id="trial-a")


class TreatmentDefinitionTests(unittest.TestCase):
    """The contract the adapter implements has to keep saying what it promised."""

    def test_the_treatment_definition_exists_and_names_its_arms(self):
        text = _flatten(TREATMENT.read_text(encoding="utf-8"))
        for arm in ("h0", "h1", "h2"):
            self.assertIn(arm, text)
        self.assertIn("raw agent", text)
        self.assertIn("per-trial reconnaissance", text)

    def test_it_prohibits_persistent_context_and_gives_the_reason(self):
        text = _flatten(TREATMENT.read_text(encoding="utf-8"))
        self.assertIn("persistent", text)
        self.assertIn("independence", text)

    def test_it_records_the_confound_rather_than_hiding_it(self):
        text = _flatten(TREATMENT.read_text(encoding="utf-8"))
        self.assertIn("cannot attribute", text)
        self.assertIn("reconnaissance", text)

    def test_it_states_that_a_null_does_not_falsify_all_of_how_do(self):
        text = _flatten(TREATMENT.read_text(encoding="utf-8"))
        self.assertIn("not how do as a whole", text)

    def test_it_keeps_the_promotion_boundary(self):
        text = _flatten(TREATMENT.read_text(encoding="utf-8"))
        self.assertIn("not how do 0.9", text)
        self.assertIn("branch may exist before the evidence earns the core", text)

    def test_the_procedure_draws_the_observation_boundary(self):
        text = _flatten(PROCEDURE.read_text(encoding="utf-8"))
        self.assertIn("observations, not conclusions", text)
        self.assertIn("task learning", text)

    def test_both_documents_admit_what_they_do_not_check(self):
        for document in (TREATMENT, PROCEDURE):
            text = _flatten(document.read_text(encoding="utf-8"))
            self.assertIn("structural", text, f"{document.name} overclaims completion")

    def test_the_experiment_does_not_ship_in_the_skill_payload(self):
        sys.path.insert(0, str(ROOT))
        import install  # noqa: E402

        self.assertNotIn("experiment", install.PAYLOAD)


if __name__ == "__main__":
    unittest.main()
