"""The generic context-kind hook: person and environment are disjoint kinds.

The pilot adapter that *uses* the environment kind lives on the `experiment`
branch and is tested there. What ships — and is therefore tested here — is the
generic machinery in `howdo.context`: kind dispatch, lifetime and authority
declarations, and the trial binding that makes an ephemeral context expire
rather than leak.
"""

import re
import tempfile
import sys
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PAYLOAD = ROOT / "plugin"
sys.path.insert(0, str(PAYLOAD / "runtime"))

from howdo import (  # noqa: E402
    ContextKindError,
    KIND_ENVIRONMENT,
    KIND_PERSON,
    complete_onboarding,
    context_kind,
    inspect_context,
)

PERSON = """---
howdo_context: "2"
context_id: pending
context_file: CONTEXT.md
skill: how-do
skill_version: "0.10.0"
onboarding: required
parent_context_id: none
---
# How Do Context

## Calibration domains

- pending

## Representation observations

- pending

## Structures that landed

- pending

## Structures that did not land

- pending
"""

ENVIRONMENT = """---
howdo_context: "2"
context_id: context_aaaaaaaaaaaa
context_file: ENVIRONMENT.md
skill: how-do
skill_version: "0.10.0"
parent_context_id: none
context_kind: environment
reconnaissance: complete
lifetime: ephemeral
write_authority: writable
trial_id: trial-a
---
# Environment Context

## Available ground

- python 3.11 and pytest are on PATH; the repo has tests/ and no CI config

## Imposed ordering

- uv sync must run before pytest; the package is not importable from a clean checkout

## Verification mechanisms

- pytest exit status over tests/ is the verifier; there is no linter configured

## Mutation and authority boundaries

- src/ is writable; vendor/ is a read-only mount; build/ is regenerated by make
"""


def _write(directory: Path, name: str, text: str) -> Path:
    path = directory / name
    path.write_text(text, encoding="utf-8")
    return path


def _relabel(path: Path, **pairs: str) -> None:
    """Rewrite frontmatter keys, inserting any the file does not carry yet.

    Replacing only what is already there would silently no-op on exactly the
    case these tests exist for: a person context has no ``context_kind`` line,
    so relabelling it has to add one.
    """
    text = path.read_text(encoding="utf-8")
    for key, value in pairs.items():
        pattern = rf"(?m)^{key}:.*$"
        if re.search(pattern, text):
            text = re.sub(pattern, f"{key}: {value}", text)
        else:
            text = text.replace("---\n", f"---\n{key}: {value}\n", 1)
    path.write_text(text, encoding="utf-8")


def _person(directory: Path) -> Path:
    path = _write(directory, "CONTEXT.md", PERSON)
    complete_onboarding(
        path,
        calibration_domain="incident response — can critique triage explanations",
        representation_observation="relation first, then rule, then executable step",
        landed_example="small boundary diagram exposed the missing handoff",
        rejected_example="taxonomy-first prose hid the concrete object",
    )
    return path


class KindDisjointnessTests(unittest.TestCase):
    """person and environment are different kinds, not two modes of one onboarding."""

    def test_absent_kind_still_means_person(self):
        with tempfile.TemporaryDirectory() as td:
            path = _person(Path(td))
            self.assertEqual(context_kind(inspect_context(path).metadata), KIND_PERSON)
            self.assertEqual(inspect_context(path).state, "ready")

    def test_a_person_context_cannot_satisfy_the_environment_validator(self):
        with tempfile.TemporaryDirectory() as td:
            path = _person(Path(td))
            self.assertEqual(inspect_context(path).state, "ready")
            _relabel(path, context_kind=KIND_ENVIRONMENT)
            status = inspect_context(path, trial_id="trial-a")
            self.assertEqual(status.state, "invalid")
            self.assertIn("missing required keys", status.reason)

    def test_an_environment_context_cannot_satisfy_the_person_validator(self):
        with tempfile.TemporaryDirectory() as td:
            path = _write(Path(td), "ENVIRONMENT.md", ENVIRONMENT)
            self.assertEqual(inspect_context(path, trial_id="trial-a").state, "ready")
            _relabel(path, context_kind=KIND_PERSON)
            status = inspect_context(path)
            self.assertNotEqual(status.state, "ready")
            self.assertIn("missing required keys", status.reason)
            self.assertIn("onboarding", status.reason)

    def test_person_evidence_does_not_settle_an_environment_context(self):
        """The headings themselves are disjoint, so the text cannot be reused."""
        with tempfile.TemporaryDirectory() as td:
            path = _person(Path(td))
            _relabel(
                path,
                context_kind=KIND_ENVIRONMENT,
                reconnaissance="complete",
                lifetime="frozen",
                write_authority="readonly",
            )
            status = inspect_context(path)
            self.assertEqual(status.state, "reconnaissance_required")
            self.assertIn("Available ground", status.reason)

    def test_onboarding_refuses_an_environment_context(self):
        with tempfile.TemporaryDirectory() as td:
            path = _write(Path(td), "ENVIRONMENT.md", ENVIRONMENT)
            with self.assertRaises(ContextKindError):
                complete_onboarding(
                    path,
                    calibration_domain="d",
                    representation_observation="r",
                    landed_example="l",
                    rejected_example="x",
                )

    def test_an_unrecognised_kind_is_invalid_not_silently_person(self):
        with tempfile.TemporaryDirectory() as td:
            path = _person(Path(td))
            _relabel(path, context_kind="organisation")
            status = inspect_context(path)
            self.assertEqual(status.state, "invalid")
            self.assertIn("unrecognised context_kind", status.reason)


class LifetimeDeclarationTests(unittest.TestCase):
    """Lifetime and authority are declared, closed vocabularies."""

    def test_an_unrecognised_lifetime_is_invalid(self):
        with tempfile.TemporaryDirectory() as td:
            path = _write(Path(td), "ENVIRONMENT.md", ENVIRONMENT)
            _relabel(path, lifetime="perennial")
            status = inspect_context(path, trial_id="trial-a")
            self.assertEqual(status.state, "invalid")
            self.assertIn("unrecognised lifetime", status.reason)

    def test_an_unrecognised_write_authority_is_invalid(self):
        with tempfile.TemporaryDirectory() as td:
            path = _write(Path(td), "ENVIRONMENT.md", ENVIRONMENT)
            _relabel(path, write_authority="mine")
            status = inspect_context(path, trial_id="trial-a")
            self.assertEqual(status.state, "invalid")
            self.assertIn("unrecognised write_authority", status.reason)


class TrialBoundaryTests(unittest.TestCase):
    """Ephemeral state cannot survive a trial boundary."""

    def test_settled_context_is_ready_for_its_own_trial(self):
        with tempfile.TemporaryDirectory() as td:
            path = _write(Path(td), "ENVIRONMENT.md", ENVIRONMENT)
            self.assertEqual(inspect_context(path, trial_id="trial-a").state, "ready")

    def test_the_next_trial_cannot_read_the_previous_trials_context(self):
        with tempfile.TemporaryDirectory() as td:
            path = _write(Path(td), "ENVIRONMENT.md", ENVIRONMENT)
            status = inspect_context(path, trial_id="trial-b")
            self.assertEqual(status.state, "expired")
            self.assertIn("did not survive the trial boundary", status.reason)

    def test_an_ephemeral_context_cannot_be_read_without_asserting_a_trial(self):
        with tempfile.TemporaryDirectory() as td:
            path = _write(Path(td), "ENVIRONMENT.md", ENVIRONMENT)
            status = inspect_context(path)
            self.assertEqual(status.state, "invalid")
            self.assertIn("must be read with the reading trial", status.reason)

    def test_an_unbound_ephemeral_context_is_invalid(self):
        with tempfile.TemporaryDirectory() as td:
            path = _write(Path(td), "ENVIRONMENT.md", ENVIRONMENT)
            _relabel(path, trial_id="none")
            status = inspect_context(path, trial_id="trial-a")
            self.assertEqual(status.state, "invalid")
            self.assertIn("not bound to a trial_id", status.reason)

    def test_a_persistent_environment_context_needs_no_trial(self):
        with tempfile.TemporaryDirectory() as td:
            path = _write(Path(td), "ENVIRONMENT.md", ENVIRONMENT)
            _relabel(path, lifetime="persistent")
            self.assertEqual(inspect_context(path).state, "ready")


if __name__ == "__main__":
    unittest.main()
