"""The How Do runtime.

Names are resolved on first use rather than at import. The package is
imported by a `PostToolUse` hook that runs on every file write in every
session, and eagerly pulling in every submodule made that hook pay ~20 ms
for modules it never touches. `from howdo import X` and
`from howdo.context import Y` both still work; only the timing changed.
"""

from __future__ import annotations

import importlib
from typing import Any

# name -> the submodule that defines it.
_ORIGIN = {
    "AUTHORITY_READONLY": "context",
    "AUTHORITY_WRITABLE": "context",
    "Admission": "core",
    "Agency": "core",
    "BoundContract": "contract",
    "CONTRACT_VERSION": "contract",
    "Check": "core",
    "Clause": "contract",
    "ContextKindError": "context",
    "ContextStatus": "context",
    "ContractError": "contract",
    "DOMAIN_VERSION": "domain",
    "DomainError": "domain",
    "DomainHow": "domain",
    "ELEMENT_TYPES": "contract",
    "EmitError": "emit",
    "Field": "contract",
    "Fizzle": "core",
    "GateEvidence": "core",
    "Host": "contract",
    "IndexEntry": "domain",
    "KIND_ENVIRONMENT": "context",
    "KIND_PERSON": "context",
    "LIFETIME_EPHEMERAL": "context",
    "LIFETIME_FROZEN": "context",
    "LIFETIME_PERSISTENT": "context",
    "MAX_COMPATIBILITY": "emit",
    "MAX_DESCRIPTION": "emit",
    "MAX_NAME": "emit",
    "OPS": "contract",
    "Observation": "core",
    "ObservationContext": "core",
    "Outcome": "core",
    "Paradigm": "core",
    "PayloadContextError": "context",
    "Request": "core",
    "RequestContract": "contract",
    "Residual": "core",
    "Resolution": "core",
    "Route": "core",
    "Rule": "contract",
    "SIGNALS_OFF": "context",
    "SIGNALS_ON": "context",
    "SPEC_FIELDS": "emit",
    "STATUS_GROUNDED": "domain",
    "STATUS_UNTESTED": "domain",
    "Settlement": "core",
    "Shape": "contract",
    "SkillBundle": "emit",
    "Staleness": "domain",
    "TARGET_CLAUDE_CODE": "emit",
    "TARGET_SPEC": "emit",
    "TYPES": "contract",
    "TemplateContextError": "context",
    "Unsupported": "contract",
    "WorkedExample": "domain",
    "WorkflowScript": "emit",
    "admit": "core",
    "bind": "contract",
    "complete_onboarding": "context",
    "context_kind": "context",
    "context_lifetime": "context",
    "decline_onboarding": "context",
    "default_store_path": "context",
    "defer_onboarding": "context",
    "domain_path": "domain",
    "ensure_context": "context",
    "fork_context": "context",
    "ground": "domain",
    "inspect_context": "context",
    "is_shared": "context",
    "issue": "domain",
    "issue_from_run": "domain",
    "load": "domain",
    "new_context_id": "context",
    "observe": "core",
    "operate": "core",
    "payload_root": "context",
    "read_frontmatter": "context",
    "read_index": "domain",
    "reindex": "domain",
    "render_skill": "emit",
    "render_workflow": "emit",
    "resolve": "core",
    "resolve_context_path": "context",
    "resolve_domain_root": "domain",
    "revise": "domain",
    "set_signals": "context",
    "settle": "core",
    "signals_enabled": "context",
    "skill_name": "emit",
    "staleness": "domain",
    "write_authority": "context",
    "write_skill": "emit",
    "write_workflow": "emit",
}


def __getattr__(name: str) -> Any:
    """Resolve an exported name by importing only the module that has it."""
    module = _ORIGIN.get(name)
    if module is None:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    value = getattr(importlib.import_module(f".{module}", __name__), name)
    globals()[name] = value  # cache, so the lookup is paid once
    return value


def __dir__() -> list[str]:
    return sorted(_ORIGIN)


__all__ = [
    "AUTHORITY_READONLY",
    "AUTHORITY_WRITABLE",
    "Admission",
    "Agency",
    "BoundContract",
    "CONTRACT_VERSION",
    "Check",
    "Clause",
    "ContextKindError",
    "ContextStatus",
    "ContractError",
    "DOMAIN_VERSION",
    "DomainError",
    "DomainHow",
    "ELEMENT_TYPES",
    "EmitError",
    "Field",
    "Fizzle",
    "GateEvidence",
    "Host",
    "IndexEntry",
    "KIND_ENVIRONMENT",
    "KIND_PERSON",
    "LIFETIME_EPHEMERAL",
    "LIFETIME_FROZEN",
    "LIFETIME_PERSISTENT",
    "MAX_COMPATIBILITY",
    "MAX_DESCRIPTION",
    "MAX_NAME",
    "OPS",
    "Observation",
    "ObservationContext",
    "Outcome",
    "Paradigm",
    "PayloadContextError",
    "Request",
    "RequestContract",
    "Residual",
    "Resolution",
    "Route",
    "Rule",
    "SIGNALS_OFF",
    "SIGNALS_ON",
    "SPEC_FIELDS",
    "STATUS_GROUNDED",
    "STATUS_UNTESTED",
    "Settlement",
    "Shape",
    "SkillBundle",
    "Staleness",
    "TARGET_CLAUDE_CODE",
    "TARGET_SPEC",
    "TYPES",
    "TemplateContextError",
    "Unsupported",
    "WorkedExample",
    "WorkflowScript",
    "admit",
    "bind",
    "complete_onboarding",
    "context_kind",
    "context_lifetime",
    "decline_onboarding",
    "default_store_path",
    "defer_onboarding",
    "domain_path",
    "ensure_context",
    "fork_context",
    "ground",
    "inspect_context",
    "is_shared",
    "issue",
    "issue_from_run",
    "load",
    "new_context_id",
    "observe",
    "operate",
    "payload_root",
    "read_frontmatter",
    "read_index",
    "reindex",
    "render_skill",
    "render_workflow",
    "resolve",
    "resolve_context_path",
    "resolve_domain_root",
    "revise",
    "set_signals",
    "settle",
    "signals_enabled",
    "skill_name",
    "staleness",
    "write_authority",
    "write_skill",
    "write_workflow",
]
