"""Publish an issued domain-how where a host will actually load it, and index it.

`emit.py` renders. This puts the result somewhere real and then answers the
question that makes recurrence possible: *what has How Do already built?*

Without this the loop cannot serve a task someone runs weekly. Every session
would re-derive the same map, re-argue the same path, and re-check the same
gate, because the thing the last session learned went to a path a caller had to
already know. A concern is recurring precisely when nobody wants to re-derive it.

Two destinations, both taken from the host's own documented layout:

* **project** -- `<project>/.claude/skills/<name>/SKILL.md` and
  `<project>/.claude/workflows/<name>.js`; shared with everyone who clones.
* **personal** -- the same two under `~/.claude` (or `$CLAUDE_CONFIG_DIR`);
  available in every project, visible only to you.

Once published, a skill loads by name and a workflow runs as `/<name>` -- which
is what turns "we worked this out once" into something invocable tomorrow.

**The index is derived, never declared.** :func:`published` scans the
destinations for artifacts carrying How Do's own marker rather than trusting a
manifest of what was *meant* to be there. A skill someone deleted stops being
listed; one someone moved in by hand starts. That is the same rule
`experiment/CROSSINGS.md` sets for the skill graph and `domain.py` sets for the
artifact index: the files are the evidence, the catalogue is a projection.

The rendered catalogue is written to the **store**, beside `CONTEXT.md`, because
the payload is replaced by every update and a reference settled inside it is
discarded with no error raised.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Any, Mapping, Sequence
import os
import re

from .context import payload_root, resolve_context_path
from .domain import STATUS_GROUNDED, DomainHow
from .emit import (
    EmitError,
    TARGET_CLAUDE_CODE,
    TARGET_SPEC,
    render_skill,
    render_workflow,
    skill_name,
)

__all__ = [
    "FORMATS",
    "SCOPE_PERSONAL",
    "SCOPE_PROJECT",
    "SUBSKILLS_BASENAME",
    "PublishError",
    "Published",
    "publish",
    "published",
    "render_reference",
    "skills_root",
    "subskills_path",
    "workflows_root",
    "write_reference",
]

SCOPE_PROJECT = "project"
SCOPE_PERSONAL = "personal"
_SCOPES = (SCOPE_PROJECT, SCOPE_PERSONAL)

FORMATS = ("skill", "workflow")

#: The catalogue lives in the store, not the payload: an update replaces the
#: skill directory wholesale.
SUBSKILLS_BASENAME = "SUBSKILLS.md"

_CONFIG_ENV = "CLAUDE_CONFIG_DIR"
_CONFIG_DIRNAME = ".claude"
_MARKER = "how-do"

# Narrow on purpose: this reads back frontmatter `emit.py` wrote, which is flat
# `key: value` lines plus a one-level `metadata:` block. It is not a YAML parser
# and must not be used as one.
_SCALAR = re.compile(r'^(?P<key>[A-Za-z_][\w.-]*):\s*(?P<value>.*)$')
_NESTED = re.compile(r'^\s+(?P<key>[A-Za-z_][\w.-]*):\s*(?P<value>.*)$')
_WORKFLOW_HEADER = re.compile(
    r'^// Generated by How Do from domain-how "(?P<concern>[^"]+)" r(?P<revision>\d+)\s*$',
    re.MULTILINE,
)


class PublishError(ValueError):
    """A destination that cannot be published to, or read back, honestly."""


def _unquote(value: str) -> str:
    value = value.strip()
    if len(value) >= 2 and value[0] == value[-1] and value[0] in "\"'":
        return value[1:-1]
    return value


def _config_home(env: Mapping[str, str] | None = None) -> Path:
    environ = os.environ if env is None else env
    configured = environ.get(_CONFIG_ENV)
    if configured:
        return Path(configured).expanduser()
    return Path.home() / _CONFIG_DIRNAME


def _scope_root(
    scope: str, *, project: str | Path | None, env: Mapping[str, str] | None
) -> Path:
    if scope not in _SCOPES:
        raise PublishError(f"unknown scope {scope!r}; expected one of {_SCOPES}")
    if scope == SCOPE_PERSONAL:
        return _config_home(env)
    if project is None:
        project = Path.cwd()
    return Path(project).expanduser() / _CONFIG_DIRNAME


def skills_root(
    scope: str = SCOPE_PROJECT,
    *,
    project: str | Path | None = None,
    env: Mapping[str, str] | None = None,
) -> Path:
    """Where a host loads skills from, for this scope."""

    return _scope_root(scope, project=project, env=env) / "skills"


def workflows_root(
    scope: str = SCOPE_PROJECT,
    *,
    project: str | Path | None = None,
    env: Mapping[str, str] | None = None,
) -> Path:
    """Where a host loads dynamic workflows from, for this scope."""

    return _scope_root(scope, project=project, env=env) / "workflows"


def subskills_path(
    *, store: str | Path | None = None, env: Mapping[str, str] | None = None
) -> Path:
    """The catalogue's path in the store, beside the durable context."""

    return resolve_context_path(store, env=os.environ if env is None else env).parent / (
        SUBSKILLS_BASENAME
    )


@dataclass(frozen=True)
class Published:
    """One artifact that is actually on disk where a host will find it."""

    concern: str
    name: str
    kind: str
    path: Path
    revision: int
    status: str
    scope: str
    #: Whether Claude may reach for this unprompted. None for a workflow, which
    #: is only ever invoked by name.
    auto_invocable: bool | None = None
    #: ``"user"`` if someone decided, ``"default"`` if the contract's
    #: consequences stood in, ``"observed"`` if this was read back off disk.
    invocation_chosen_by: str = "observed"

    @property
    def command(self) -> str:
        """What someone types to run it again -- the point of publishing at all."""
        return f"/{self.name}"


def _read_frontmatter(text: str) -> dict[str, Any]:
    if not text.startswith("---"):
        return {}
    end = text.find("\n---", 3)
    if end == -1:
        return {}
    data: dict[str, Any] = {}
    current: dict[str, Any] | None = None
    for line in text[3:end].splitlines():
        if not line.strip() or line.lstrip().startswith("#"):
            continue
        nested = _NESTED.match(line)
        if nested and current is not None:
            current[nested.group("key")] = _unquote(nested.group("value"))
            continue
        scalar = _SCALAR.match(line)
        if not scalar:
            continue
        key, value = scalar.group("key"), scalar.group("value").strip()
        if value == "":
            current = {}
            data[key] = current
        else:
            current = None
            data[key] = _unquote(value)
    return data


def _published_skills(root: Path, scope: str) -> list[Published]:
    found: list[Published] = []
    if not root.is_dir():
        return found
    for candidate in sorted(root.glob("*/SKILL.md")):
        try:
            front = _read_frontmatter(candidate.read_text(encoding="utf-8"))
        except OSError:
            continue
        metadata = front.get("metadata")
        if not isinstance(metadata, Mapping) or metadata.get("issued_by") != _MARKER:
            continue  # somebody else's skill; not ours to catalogue
        try:
            revision = int(metadata.get("revision", 1))
        except (TypeError, ValueError):
            revision = 1
        found.append(
            Published(
                concern=str(metadata.get("concern", candidate.parent.name)),
                name=candidate.parent.name,
                kind="skill",
                path=candidate,
                revision=revision,
                status=str(metadata.get("status", "unknown")),
                scope=scope,
                # Read from the file rather than recomputed: what is installed is
                # what governs, even if someone edited it after publishing.
                auto_invocable=str(front.get("disable-model-invocation", "")).lower()
                not in ("true", "yes", "on", "1"),
                invocation_chosen_by="observed",
            )
        )
    return found


def _published_workflows(root: Path, scope: str) -> list[Published]:
    found: list[Published] = []
    if not root.is_dir():
        return found
    for candidate in sorted(root.glob("*.js")):
        try:
            source = candidate.read_text(encoding="utf-8")
        except OSError:
            continue
        header = _WORKFLOW_HEADER.search(source)
        if header is None:
            continue
        found.append(
            Published(
                concern=header.group("concern"),
                name=candidate.stem,
                kind="workflow",
                path=candidate,
                revision=int(header.group("revision")),
                status=STATUS_GROUNDED if "UNTESTED" not in source else "untested",
                scope=scope,
            )
        )
    return found


def published(
    scope: str = SCOPE_PROJECT,
    *,
    project: str | Path | None = None,
    env: Mapping[str, str] | None = None,
) -> tuple[Published, ...]:
    """What How Do has actually built and left where a host can load it.

    Read from the destinations rather than from a record of intent, so a deleted
    artifact stops being listed and a hand-placed one starts.
    """

    entries = _published_skills(skills_root(scope, project=project, env=env), scope)
    entries += _published_workflows(workflows_root(scope, project=project, env=env), scope)
    return tuple(sorted(entries, key=lambda e: (e.concern, e.kind)))


def publish(
    how: DomainHow,
    *,
    scope: str = SCOPE_PROJECT,
    project: str | Path | None = None,
    env: Mapping[str, str] | None = None,
    formats: Sequence[str] = FORMATS,
    allow_untested: bool = False,
    overwrite: bool = False,
    license: str | None = None,
    disable_model_invocation: bool | None = None,
) -> tuple[Published, ...]:
    """Build the skill and workflow for a concern, where the host will find them.

    The frontmatter *target* follows the destination rather than the caller's
    taste: a skill written into a `.claude/skills` directory is being installed
    into Claude Code, so that is the vocabulary it gets.

    Whether Claude may then reach for it unprompted is a different question and
    not the issuer's to settle. The person who worked the concern out was in the
    room for it and knows whether it belongs in Claude's reach; pass
    ``disable_model_invocation`` to say so. Left ``None``, the contract's
    consequences stand in and the result says ``invocation_chosen_by ==
    "default"`` -- which is a prompt to ask them, not their answer.

    Nothing is published anywhere near the How Do payload.
    """

    unknown = sorted(set(formats) - set(FORMATS))
    if unknown:
        raise PublishError(f"unknown formats: {unknown}; expected from {FORMATS}")
    if not formats:
        raise PublishError("publishing nothing is not a destination")

    name = skill_name(how.concern)
    results: list[Published] = []

    if "skill" in formats:
        root = skills_root(scope, project=project, env=env)
        _guard_destination(root)
        bundle = render_skill(
            how,
            allow_untested=allow_untested,
            target=TARGET_CLAUDE_CODE,
            license=license,
            disable_model_invocation=disable_model_invocation,
        )
        directory = root / bundle.name
        target = directory / "SKILL.md"
        _guard_overwrite(target, overwrite)
        directory.mkdir(parents=True, exist_ok=True)
        target.write_text(bundle.body, encoding="utf-8")
        results.append(
            Published(
                concern=how.concern,
                name=bundle.name,
                kind="skill",
                path=target,
                revision=how.revision,
                status=how.status,
                scope=scope,
                auto_invocable=bundle.auto_invocable,
                invocation_chosen_by=bundle.invocation_chosen_by,
            )
        )

    if "workflow" in formats:
        root = workflows_root(scope, project=project, env=env)
        _guard_destination(root)
        script = render_workflow(how, allow_untested=allow_untested)
        target = root / f"{script.name}.js"
        _guard_overwrite(target, overwrite)
        root.mkdir(parents=True, exist_ok=True)
        target.write_text(script.source, encoding="utf-8")
        results.append(
            Published(
                concern=how.concern,
                name=script.name,
                kind="workflow",
                path=target,
                revision=how.revision,
                status=how.status,
                scope=scope,
            )
        )

    return tuple(results)


def _guard_destination(root: Path) -> None:
    payload = payload_root(root)
    if payload is not None:
        raise PublishError(
            f"{root} is inside a skill payload at {payload}; the next install would "
            "replace it with no error raised"
        )


def _guard_overwrite(target: Path, overwrite: bool) -> None:
    if target.exists() and not overwrite:
        raise PublishError(
            f"{target} already exists; pass overwrite=True to replace it. A published "
            "artifact someone may already be invoking is not silently swapped."
        )


def render_reference(entries: Sequence[Published]) -> str:
    """Render the catalogue How Do reads to know what it has already built."""

    lines = [
        "# Subskills and workflows issued by How Do",
        "",
        "Derived by scanning the destinations, not from a record of intent: an",
        "artifact deleted from disk is absent here, and one added by hand appears.",
        "Re-generate rather than editing this file.",
        "",
    ]
    if not entries:
        lines += [
            "Nothing published yet. A concern earns an entry once a domain-how for it",
            "has been grounded by an observed run and published.",
            "",
        ]
        return "\n".join(lines)

    lines += [
        "| concern | invoke | kind | r | status | reachable by | scope |",
        "|---|---|---|---|---|---|---|",
    ]
    for entry in entries:
        if entry.kind == "workflow" or entry.auto_invocable is None:
            reach = "you"
        else:
            reach = "you or Claude" if entry.auto_invocable else "you only"
        lines.append(
            f"| {entry.concern} | `{entry.command}` | {entry.kind} | {entry.revision} "
            f"| {entry.status} | {reach} | {entry.scope} |"
        )
    lines += [
        "",
        "## Using these",
        "",
        "Load the entry for a concern before establishing anything fresh about it —",
        "that is what makes a recurring task cheap the second time. An entry marked",
        "`untested` was published for review and has not been confirmed by an observed",
        "run; treat its steps as a proposal.",
        "",
        "**Reachable by** is a decision someone made, not a property of the work.",
        "\"You only\" means Claude will not load it unprompted; \"you or Claude\" means it",
        "can be reached for when relevant. Either is legitimate and it is the person's",
        "call \u2014 change it by publishing again with the other choice.",
        "",
        "A workflow entry runs as its command directly. To repeat one on a cadence, use",
        "the host's own scheduling rather than anything here: How Do issues and indexes",
        "artifacts, it does not run a clock.",
        "",
    ]
    return "\n".join(lines)


def write_reference(
    entries: Sequence[Published] | None = None,
    *,
    scope: str = SCOPE_PROJECT,
    project: str | Path | None = None,
    store: str | Path | None = None,
    env: Mapping[str, str] | None = None,
) -> Path:
    """Write the catalogue into the store, beside the durable context."""

    if entries is None:
        entries = published(scope, project=project, env=env)
    target = subskills_path(store=store, env=env)
    payload = payload_root(target)
    if payload is not None:
        raise PublishError(
            f"{target} is inside the skill payload at {payload}; an update would "
            "discard the catalogue with no error raised"
        )
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(render_reference(entries), encoding="utf-8")
    return target
